[package]
name = "fennec-reflector"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-interner = { path = "../interner" }
fennec-span = { path = "../span" }
fennec-ast = { path = "../ast" }
fennec-ast-utils = { path = "../ast-utils" }
fennec-walker = { path = "../walker" }
fennec-source = { path = "../source" }
fennec-semantics = { path = "../semantics" }
fennec-typing = { path = "../typing" }
fennec-reflection = { path = "../reflection" }
ahash = { workspace = true }
