php-version = "8.1"

[source]
paths = ["composer", "scripts"]
includes = ["vendor"]
excludes = ["scripts/local"]

[linter.rules]
ambiguous-function-call = { enabled = false }
cyclomatic-complexity = { threshold = 20 }
kan-defect = { threshold = 1.9 }
halstead = { effort-threshold = 7000 }
literal-named-argument = { enabled = false }
too-many-enum-cases = { threshold = 30 }
