[package]
name = "fennec-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-reporting = { path = "../reporting" }
fennec-interner = { path = "../interner" }
fennec-source = { path = "../source" }
fennec-fixer = { path = "../fixer" }
fennec-service = { path = "../service" }
fennec-feedback = { path = "../feedback" }
serde = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
ahash = { workspace = true }
