[package]
name = "fennec-formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
ahash = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
bitflags = { workspace = true }
fennec-ast = { path = "../ast" }
fennec-source = { path = "../source" }
fennec-span = { path = "../span" }
fennec-token = { path = "../token" }
fennec-interner = { path = "../interner" }
